#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegraDeNegocio
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SITE_BASE")]
	public partial class BancoDeDadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertErro(Erro instance);
    partial void UpdateErro(Erro instance);
    partial void DeleteErro(Erro instance);
    partial void InsertFale_Conosco_Assunto(Fale_Conosco_Assunto instance);
    partial void UpdateFale_Conosco_Assunto(Fale_Conosco_Assunto instance);
    partial void DeleteFale_Conosco_Assunto(Fale_Conosco_Assunto instance);
    partial void InsertFale_Conosco_Email(Fale_Conosco_Email instance);
    partial void UpdateFale_Conosco_Email(Fale_Conosco_Email instance);
    partial void DeleteFale_Conosco_Email(Fale_Conosco_Email instance);
    partial void InsertFale_Conosco_Formularios_Enviado(Fale_Conosco_Formularios_Enviado instance);
    partial void UpdateFale_Conosco_Formularios_Enviado(Fale_Conosco_Formularios_Enviado instance);
    partial void DeleteFale_Conosco_Formularios_Enviado(Fale_Conosco_Formularios_Enviado instance);
    partial void InsertMenuSite(MenuSite instance);
    partial void UpdateMenuSite(MenuSite instance);
    partial void DeleteMenuSite(MenuSite instance);
    partial void InsertNoticia(Noticia instance);
    partial void UpdateNoticia(Noticia instance);
    partial void DeleteNoticia(Noticia instance);
    partial void InsertPagina(Pagina instance);
    partial void UpdatePagina(Pagina instance);
    partial void DeletePagina(Pagina instance);
    #endregion
	
		
		public BancoDeDadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDeDadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDeDadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDeDadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Erro> Erros
		{
			get
			{
				return this.GetTable<Erro>();
			}
		}
		
		public System.Data.Linq.Table<Fale_Conosco_Assunto> Fale_Conosco_Assuntos
		{
			get
			{
				return this.GetTable<Fale_Conosco_Assunto>();
			}
		}
		
		public System.Data.Linq.Table<Fale_Conosco_Email> Fale_Conosco_Emails
		{
			get
			{
				return this.GetTable<Fale_Conosco_Email>();
			}
		}
		
		public System.Data.Linq.Table<Fale_Conosco_Formularios_Enviado> Fale_Conosco_Formularios_Enviados
		{
			get
			{
				return this.GetTable<Fale_Conosco_Formularios_Enviado>();
			}
		}
		
		public System.Data.Linq.Table<MenuSite> MenuSites
		{
			get
			{
				return this.GetTable<MenuSite>();
			}
		}
		
		public System.Data.Linq.Table<Noticia> Noticias
		{
			get
			{
				return this.GetTable<Noticia>();
			}
		}
		
		public System.Data.Linq.Table<Pagina> Paginas
		{
			get
			{
				return this.GetTable<Pagina>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Erros")]
	public partial class Erro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CodErro;
		
		private System.Nullable<System.Guid> _UserId;
		
		private System.Nullable<System.DateTime> _DataCadastro;
		
		private string _IP;
		
		private string _Pagina;
		
		private string _Mensagem;
		
		private string _StackTrace;
		
		private System.Nullable<bool> _Resolvido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodErroChanging(long value);
    partial void OnCodErroChanged();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnDataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCadastroChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnPaginaChanging(string value);
    partial void OnPaginaChanged();
    partial void OnMensagemChanging(string value);
    partial void OnMensagemChanged();
    partial void OnStackTraceChanging(string value);
    partial void OnStackTraceChanged();
    partial void OnResolvidoChanging(System.Nullable<bool> value);
    partial void OnResolvidoChanged();
    #endregion
		
		public Erro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodErro", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CodErro
		{
			get
			{
				return this._CodErro;
			}
			set
			{
				if ((this._CodErro != value))
				{
					this.OnCodErroChanging(value);
					this.SendPropertyChanging();
					this._CodErro = value;
					this.SendPropertyChanged("CodErro");
					this.OnCodErroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(100)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pagina", DbType="VarChar(250)")]
		public string Pagina
		{
			get
			{
				return this._Pagina;
			}
			set
			{
				if ((this._Pagina != value))
				{
					this.OnPaginaChanging(value);
					this.SendPropertyChanging();
					this._Pagina = value;
					this.SendPropertyChanged("Pagina");
					this.OnPaginaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensagem", DbType="VarChar(4000)")]
		public string Mensagem
		{
			get
			{
				return this._Mensagem;
			}
			set
			{
				if ((this._Mensagem != value))
				{
					this.OnMensagemChanging(value);
					this.SendPropertyChanging();
					this._Mensagem = value;
					this.SendPropertyChanged("Mensagem");
					this.OnMensagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StackTrace", DbType="VarChar(8000)")]
		public string StackTrace
		{
			get
			{
				return this._StackTrace;
			}
			set
			{
				if ((this._StackTrace != value))
				{
					this.OnStackTraceChanging(value);
					this.SendPropertyChanging();
					this._StackTrace = value;
					this.SendPropertyChanged("StackTrace");
					this.OnStackTraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resolvido", DbType="Bit")]
		public System.Nullable<bool> Resolvido
		{
			get
			{
				return this._Resolvido;
			}
			set
			{
				if ((this._Resolvido != value))
				{
					this.OnResolvidoChanging(value);
					this.SendPropertyChanging();
					this._Resolvido = value;
					this.SendPropertyChanged("Resolvido");
					this.OnResolvidoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fale_Conosco_Assuntos")]
	public partial class Fale_Conosco_Assunto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AssuntoID;
		
		private string _Nome;
		
		private bool _IsAtivo;
		
		private EntitySet<Fale_Conosco_Email> _Fale_Conosco_Emails;
		
		private EntitySet<Fale_Conosco_Formularios_Enviado> _Fale_Conosco_Formularios_Enviados;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAssuntoIDChanging(int value);
    partial void OnAssuntoIDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnIsAtivoChanging(bool value);
    partial void OnIsAtivoChanged();
    #endregion
		
		public Fale_Conosco_Assunto()
		{
			this._Fale_Conosco_Emails = new EntitySet<Fale_Conosco_Email>(new Action<Fale_Conosco_Email>(this.attach_Fale_Conosco_Emails), new Action<Fale_Conosco_Email>(this.detach_Fale_Conosco_Emails));
			this._Fale_Conosco_Formularios_Enviados = new EntitySet<Fale_Conosco_Formularios_Enviado>(new Action<Fale_Conosco_Formularios_Enviado>(this.attach_Fale_Conosco_Formularios_Enviados), new Action<Fale_Conosco_Formularios_Enviado>(this.detach_Fale_Conosco_Formularios_Enviados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssuntoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AssuntoID
		{
			get
			{
				return this._AssuntoID;
			}
			set
			{
				if ((this._AssuntoID != value))
				{
					this.OnAssuntoIDChanging(value);
					this.SendPropertyChanging();
					this._AssuntoID = value;
					this.SendPropertyChanged("AssuntoID");
					this.OnAssuntoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAtivo", DbType="Bit NOT NULL")]
		public bool IsAtivo
		{
			get
			{
				return this._IsAtivo;
			}
			set
			{
				if ((this._IsAtivo != value))
				{
					this.OnIsAtivoChanging(value);
					this.SendPropertyChanging();
					this._IsAtivo = value;
					this.SendPropertyChanged("IsAtivo");
					this.OnIsAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fale_Conosco_Assunto_Fale_Conosco_Email", Storage="_Fale_Conosco_Emails", ThisKey="AssuntoID", OtherKey="AssuntoID")]
		public EntitySet<Fale_Conosco_Email> Fale_Conosco_Emails
		{
			get
			{
				return this._Fale_Conosco_Emails;
			}
			set
			{
				this._Fale_Conosco_Emails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fale_Conosco_Assunto_Fale_Conosco_Formularios_Enviado", Storage="_Fale_Conosco_Formularios_Enviados", ThisKey="AssuntoID", OtherKey="AssuntoID")]
		public EntitySet<Fale_Conosco_Formularios_Enviado> Fale_Conosco_Formularios_Enviados
		{
			get
			{
				return this._Fale_Conosco_Formularios_Enviados;
			}
			set
			{
				this._Fale_Conosco_Formularios_Enviados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fale_Conosco_Emails(Fale_Conosco_Email entity)
		{
			this.SendPropertyChanging();
			entity.Fale_Conosco_Assunto = this;
		}
		
		private void detach_Fale_Conosco_Emails(Fale_Conosco_Email entity)
		{
			this.SendPropertyChanging();
			entity.Fale_Conosco_Assunto = null;
		}
		
		private void attach_Fale_Conosco_Formularios_Enviados(Fale_Conosco_Formularios_Enviado entity)
		{
			this.SendPropertyChanging();
			entity.Fale_Conosco_Assunto = this;
		}
		
		private void detach_Fale_Conosco_Formularios_Enviados(Fale_Conosco_Formularios_Enviado entity)
		{
			this.SendPropertyChanging();
			entity.Fale_Conosco_Assunto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fale_Conosco_Emails")]
	public partial class Fale_Conosco_Email : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _EmailID;
		
		private int _AssuntoID;
		
		private string _Email;
		
		private string _Nome;
		
		private EntityRef<Fale_Conosco_Assunto> _Fale_Conosco_Assunto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailIDChanging(int value);
    partial void OnEmailIDChanged();
    partial void OnAssuntoIDChanging(int value);
    partial void OnAssuntoIDChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    #endregion
		
		public Fale_Conosco_Email()
		{
			this._Fale_Conosco_Assunto = default(EntityRef<Fale_Conosco_Assunto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int EmailID
		{
			get
			{
				return this._EmailID;
			}
			set
			{
				if ((this._EmailID != value))
				{
					this.OnEmailIDChanging(value);
					this.SendPropertyChanging();
					this._EmailID = value;
					this.SendPropertyChanged("EmailID");
					this.OnEmailIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssuntoID", DbType="Int NOT NULL")]
		public int AssuntoID
		{
			get
			{
				return this._AssuntoID;
			}
			set
			{
				if ((this._AssuntoID != value))
				{
					if (this._Fale_Conosco_Assunto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAssuntoIDChanging(value);
					this.SendPropertyChanging();
					this._AssuntoID = value;
					this.SendPropertyChanged("AssuntoID");
					this.OnAssuntoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fale_Conosco_Assunto_Fale_Conosco_Email", Storage="_Fale_Conosco_Assunto", ThisKey="AssuntoID", OtherKey="AssuntoID", IsForeignKey=true)]
		public Fale_Conosco_Assunto Fale_Conosco_Assunto
		{
			get
			{
				return this._Fale_Conosco_Assunto.Entity;
			}
			set
			{
				Fale_Conosco_Assunto previousValue = this._Fale_Conosco_Assunto.Entity;
				if (((previousValue != value) 
							|| (this._Fale_Conosco_Assunto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fale_Conosco_Assunto.Entity = null;
						previousValue.Fale_Conosco_Emails.Remove(this);
					}
					this._Fale_Conosco_Assunto.Entity = value;
					if ((value != null))
					{
						value.Fale_Conosco_Emails.Add(this);
						this._AssuntoID = value.AssuntoID;
					}
					else
					{
						this._AssuntoID = default(int);
					}
					this.SendPropertyChanged("Fale_Conosco_Assunto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fale_Conosco_Formularios_Enviados")]
	public partial class Fale_Conosco_Formularios_Enviado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _FormularioID;
		
		private System.DateTime _DataEnvio;
		
		private string _IP;
		
		private string _Nome;
		
		private string _Email;
		
		private string _Telefone;
		
		private int _AssuntoID;
		
		private string _Mensagem;
		
		private EntityRef<Fale_Conosco_Assunto> _Fale_Conosco_Assunto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFormularioIDChanging(long value);
    partial void OnFormularioIDChanged();
    partial void OnDataEnvioChanging(System.DateTime value);
    partial void OnDataEnvioChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnAssuntoIDChanging(int value);
    partial void OnAssuntoIDChanged();
    partial void OnMensagemChanging(string value);
    partial void OnMensagemChanged();
    #endregion
		
		public Fale_Conosco_Formularios_Enviado()
		{
			this._Fale_Conosco_Assunto = default(EntityRef<Fale_Conosco_Assunto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormularioID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long FormularioID
		{
			get
			{
				return this._FormularioID;
			}
			set
			{
				if ((this._FormularioID != value))
				{
					this.OnFormularioIDChanging(value);
					this.SendPropertyChanging();
					this._FormularioID = value;
					this.SendPropertyChanged("FormularioID");
					this.OnFormularioIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEnvio", DbType="DateTime NOT NULL")]
		public System.DateTime DataEnvio
		{
			get
			{
				return this._DataEnvio;
			}
			set
			{
				if ((this._DataEnvio != value))
				{
					this.OnDataEnvioChanging(value);
					this.SendPropertyChanging();
					this._DataEnvio = value;
					this.SendPropertyChanged("DataEnvio");
					this.OnDataEnvioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(20)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssuntoID", DbType="Int NOT NULL")]
		public int AssuntoID
		{
			get
			{
				return this._AssuntoID;
			}
			set
			{
				if ((this._AssuntoID != value))
				{
					if (this._Fale_Conosco_Assunto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAssuntoIDChanging(value);
					this.SendPropertyChanging();
					this._AssuntoID = value;
					this.SendPropertyChanged("AssuntoID");
					this.OnAssuntoIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mensagem", DbType="VarChar(MAX)")]
		public string Mensagem
		{
			get
			{
				return this._Mensagem;
			}
			set
			{
				if ((this._Mensagem != value))
				{
					this.OnMensagemChanging(value);
					this.SendPropertyChanging();
					this._Mensagem = value;
					this.SendPropertyChanged("Mensagem");
					this.OnMensagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fale_Conosco_Assunto_Fale_Conosco_Formularios_Enviado", Storage="_Fale_Conosco_Assunto", ThisKey="AssuntoID", OtherKey="AssuntoID", IsForeignKey=true)]
		public Fale_Conosco_Assunto Fale_Conosco_Assunto
		{
			get
			{
				return this._Fale_Conosco_Assunto.Entity;
			}
			set
			{
				Fale_Conosco_Assunto previousValue = this._Fale_Conosco_Assunto.Entity;
				if (((previousValue != value) 
							|| (this._Fale_Conosco_Assunto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fale_Conosco_Assunto.Entity = null;
						previousValue.Fale_Conosco_Formularios_Enviados.Remove(this);
					}
					this._Fale_Conosco_Assunto.Entity = value;
					if ((value != null))
					{
						value.Fale_Conosco_Formularios_Enviados.Add(this);
						this._AssuntoID = value.AssuntoID;
					}
					else
					{
						this._AssuntoID = default(int);
					}
					this.SendPropertyChanged("Fale_Conosco_Assunto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MenuSite")]
	public partial class MenuSite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MenuSiteID;
		
		private string _Texto;
		
		private string _Link;
		
		private bool _AbreNovaJanela;
		
		private int _Ordem;
		
		private System.Nullable<int> _MenuSiteIDPai;
		
		private EntitySet<MenuSite> _MenuSites;
		
		private EntityRef<MenuSite> _MenuSite1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuSiteIDChanging(int value);
    partial void OnMenuSiteIDChanged();
    partial void OnTextoChanging(string value);
    partial void OnTextoChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnAbreNovaJanelaChanging(bool value);
    partial void OnAbreNovaJanelaChanged();
    partial void OnOrdemChanging(int value);
    partial void OnOrdemChanged();
    partial void OnMenuSiteIDPaiChanging(System.Nullable<int> value);
    partial void OnMenuSiteIDPaiChanged();
    #endregion
		
		public MenuSite()
		{
			this._MenuSites = new EntitySet<MenuSite>(new Action<MenuSite>(this.attach_MenuSites), new Action<MenuSite>(this.detach_MenuSites));
			this._MenuSite1 = default(EntityRef<MenuSite>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuSiteID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MenuSiteID
		{
			get
			{
				return this._MenuSiteID;
			}
			set
			{
				if ((this._MenuSiteID != value))
				{
					this.OnMenuSiteIDChanging(value);
					this.SendPropertyChanging();
					this._MenuSiteID = value;
					this.SendPropertyChanged("MenuSiteID");
					this.OnMenuSiteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Texto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Texto
		{
			get
			{
				return this._Texto;
			}
			set
			{
				if ((this._Texto != value))
				{
					this.OnTextoChanging(value);
					this.SendPropertyChanging();
					this._Texto = value;
					this.SendPropertyChanged("Texto");
					this.OnTextoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AbreNovaJanela", DbType="Bit NOT NULL")]
		public bool AbreNovaJanela
		{
			get
			{
				return this._AbreNovaJanela;
			}
			set
			{
				if ((this._AbreNovaJanela != value))
				{
					this.OnAbreNovaJanelaChanging(value);
					this.SendPropertyChanging();
					this._AbreNovaJanela = value;
					this.SendPropertyChanged("AbreNovaJanela");
					this.OnAbreNovaJanelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ordem", DbType="Int NOT NULL")]
		public int Ordem
		{
			get
			{
				return this._Ordem;
			}
			set
			{
				if ((this._Ordem != value))
				{
					this.OnOrdemChanging(value);
					this.SendPropertyChanging();
					this._Ordem = value;
					this.SendPropertyChanged("Ordem");
					this.OnOrdemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuSiteIDPai", DbType="Int")]
		public System.Nullable<int> MenuSiteIDPai
		{
			get
			{
				return this._MenuSiteIDPai;
			}
			set
			{
				if ((this._MenuSiteIDPai != value))
				{
					if (this._MenuSite1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMenuSiteIDPaiChanging(value);
					this.SendPropertyChanging();
					this._MenuSiteIDPai = value;
					this.SendPropertyChanged("MenuSiteIDPai");
					this.OnMenuSiteIDPaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuSite_MenuSite", Storage="_MenuSites", ThisKey="MenuSiteID", OtherKey="MenuSiteIDPai")]
		public EntitySet<MenuSite> MenuSites
		{
			get
			{
				return this._MenuSites;
			}
			set
			{
				this._MenuSites.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MenuSite_MenuSite", Storage="_MenuSite1", ThisKey="MenuSiteIDPai", OtherKey="MenuSiteID", IsForeignKey=true)]
		public MenuSite MenuSite1
		{
			get
			{
				return this._MenuSite1.Entity;
			}
			set
			{
				MenuSite previousValue = this._MenuSite1.Entity;
				if (((previousValue != value) 
							|| (this._MenuSite1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MenuSite1.Entity = null;
						previousValue.MenuSites.Remove(this);
					}
					this._MenuSite1.Entity = value;
					if ((value != null))
					{
						value.MenuSites.Add(this);
						this._MenuSiteIDPai = value.MenuSiteID;
					}
					else
					{
						this._MenuSiteIDPai = default(Nullable<int>);
					}
					this.SendPropertyChanged("MenuSite1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MenuSites(MenuSite entity)
		{
			this.SendPropertyChanging();
			entity.MenuSite1 = this;
		}
		
		private void detach_MenuSites(MenuSite entity)
		{
			this.SendPropertyChanging();
			entity.MenuSite1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Noticias")]
	public partial class Noticia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NoticiaID;
		
		private System.DateTime _Data;
		
		private string _Titulo;
		
		private string _Resumo;
		
		private string _HTML;
		
		private bool _IsAtiva;
		
		private System.DateTime _DataCriacao;
		
		private System.Nullable<System.DateTime> _DataAtualizacao;
		
		private System.Nullable<int> _NoticiaIDOriginal;
		
		private System.DateTime _DataInicioPublicacao;
		
		private System.Nullable<System.DateTime> _DataTerminoPublicacao;
		
		private string _Imagem;
		
		private string _ImagemShareFAcebook;
		
		private EntitySet<Noticia> _Noticias;
		
		private EntityRef<Noticia> _Noticia1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNoticiaIDChanging(int value);
    partial void OnNoticiaIDChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnResumoChanging(string value);
    partial void OnResumoChanged();
    partial void OnHTMLChanging(string value);
    partial void OnHTMLChanged();
    partial void OnIsAtivaChanging(bool value);
    partial void OnIsAtivaChanged();
    partial void OnDataCriacaoChanging(System.DateTime value);
    partial void OnDataCriacaoChanged();
    partial void OnDataAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataAtualizacaoChanged();
    partial void OnNoticiaIDOriginalChanging(System.Nullable<int> value);
    partial void OnNoticiaIDOriginalChanged();
    partial void OnDataInicioPublicacaoChanging(System.DateTime value);
    partial void OnDataInicioPublicacaoChanged();
    partial void OnDataTerminoPublicacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataTerminoPublicacaoChanged();
    partial void OnImagemChanging(string value);
    partial void OnImagemChanged();
    partial void OnImagemShareFAcebookChanging(string value);
    partial void OnImagemShareFAcebookChanged();
    #endregion
		
		public Noticia()
		{
			this._Noticias = new EntitySet<Noticia>(new Action<Noticia>(this.attach_Noticias), new Action<Noticia>(this.detach_Noticias));
			this._Noticia1 = default(EntityRef<Noticia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticiaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NoticiaID
		{
			get
			{
				return this._NoticiaID;
			}
			set
			{
				if ((this._NoticiaID != value))
				{
					this.OnNoticiaIDChanging(value);
					this.SendPropertyChanging();
					this._NoticiaID = value;
					this.SendPropertyChanged("NoticiaID");
					this.OnNoticiaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="DateTime NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resumo", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string Resumo
		{
			get
			{
				return this._Resumo;
			}
			set
			{
				if ((this._Resumo != value))
				{
					this.OnResumoChanging(value);
					this.SendPropertyChanging();
					this._Resumo = value;
					this.SendPropertyChanged("Resumo");
					this.OnResumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTML", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HTML
		{
			get
			{
				return this._HTML;
			}
			set
			{
				if ((this._HTML != value))
				{
					this.OnHTMLChanging(value);
					this.SendPropertyChanging();
					this._HTML = value;
					this.SendPropertyChanged("HTML");
					this.OnHTMLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAtiva", DbType="Bit NOT NULL")]
		public bool IsAtiva
		{
			get
			{
				return this._IsAtiva;
			}
			set
			{
				if ((this._IsAtiva != value))
				{
					this.OnIsAtivaChanging(value);
					this.SendPropertyChanging();
					this._IsAtiva = value;
					this.SendPropertyChanged("IsAtiva");
					this.OnIsAtivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCriacao", DbType="DateTime NOT NULL")]
		public System.DateTime DataCriacao
		{
			get
			{
				return this._DataCriacao;
			}
			set
			{
				if ((this._DataCriacao != value))
				{
					this.OnDataCriacaoChanging(value);
					this.SendPropertyChanging();
					this._DataCriacao = value;
					this.SendPropertyChanged("DataCriacao");
					this.OnDataCriacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAtualizacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataAtualizacao
		{
			get
			{
				return this._DataAtualizacao;
			}
			set
			{
				if ((this._DataAtualizacao != value))
				{
					this.OnDataAtualizacaoChanging(value);
					this.SendPropertyChanging();
					this._DataAtualizacao = value;
					this.SendPropertyChanged("DataAtualizacao");
					this.OnDataAtualizacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticiaIDOriginal", DbType="Int")]
		public System.Nullable<int> NoticiaIDOriginal
		{
			get
			{
				return this._NoticiaIDOriginal;
			}
			set
			{
				if ((this._NoticiaIDOriginal != value))
				{
					if (this._Noticia1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNoticiaIDOriginalChanging(value);
					this.SendPropertyChanging();
					this._NoticiaIDOriginal = value;
					this.SendPropertyChanged("NoticiaIDOriginal");
					this.OnNoticiaIDOriginalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataInicioPublicacao", DbType="DateTime NOT NULL")]
		public System.DateTime DataInicioPublicacao
		{
			get
			{
				return this._DataInicioPublicacao;
			}
			set
			{
				if ((this._DataInicioPublicacao != value))
				{
					this.OnDataInicioPublicacaoChanging(value);
					this.SendPropertyChanging();
					this._DataInicioPublicacao = value;
					this.SendPropertyChanged("DataInicioPublicacao");
					this.OnDataInicioPublicacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataTerminoPublicacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataTerminoPublicacao
		{
			get
			{
				return this._DataTerminoPublicacao;
			}
			set
			{
				if ((this._DataTerminoPublicacao != value))
				{
					this.OnDataTerminoPublicacaoChanging(value);
					this.SendPropertyChanging();
					this._DataTerminoPublicacao = value;
					this.SendPropertyChanged("DataTerminoPublicacao");
					this.OnDataTerminoPublicacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagem", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Imagem
		{
			get
			{
				return this._Imagem;
			}
			set
			{
				if ((this._Imagem != value))
				{
					this.OnImagemChanging(value);
					this.SendPropertyChanging();
					this._Imagem = value;
					this.SendPropertyChanged("Imagem");
					this.OnImagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagemShareFAcebook", DbType="VarChar(255)")]
		public string ImagemShareFAcebook
		{
			get
			{
				return this._ImagemShareFAcebook;
			}
			set
			{
				if ((this._ImagemShareFAcebook != value))
				{
					this.OnImagemShareFAcebookChanging(value);
					this.SendPropertyChanging();
					this._ImagemShareFAcebook = value;
					this.SendPropertyChanged("ImagemShareFAcebook");
					this.OnImagemShareFAcebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Noticia_Noticia", Storage="_Noticias", ThisKey="NoticiaID", OtherKey="NoticiaIDOriginal")]
		public EntitySet<Noticia> Noticias
		{
			get
			{
				return this._Noticias;
			}
			set
			{
				this._Noticias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Noticia_Noticia", Storage="_Noticia1", ThisKey="NoticiaIDOriginal", OtherKey="NoticiaID", IsForeignKey=true)]
		public Noticia Noticia1
		{
			get
			{
				return this._Noticia1.Entity;
			}
			set
			{
				Noticia previousValue = this._Noticia1.Entity;
				if (((previousValue != value) 
							|| (this._Noticia1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Noticia1.Entity = null;
						previousValue.Noticias.Remove(this);
					}
					this._Noticia1.Entity = value;
					if ((value != null))
					{
						value.Noticias.Add(this);
						this._NoticiaIDOriginal = value.NoticiaID;
					}
					else
					{
						this._NoticiaIDOriginal = default(Nullable<int>);
					}
					this.SendPropertyChanged("Noticia1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Noticias(Noticia entity)
		{
			this.SendPropertyChanging();
			entity.Noticia1 = this;
		}
		
		private void detach_Noticias(Noticia entity)
		{
			this.SendPropertyChanging();
			entity.Noticia1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paginas")]
	public partial class Pagina : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PaginaID;
		
		private string _Url;
		
		private string _Titulo;
		
		private string _Resumo;
		
		private string _Imagem;
		
		private string _HTML;
		
		private bool _IsAtiva;
		
		private System.DateTime _DataCriacao;
		
		private System.Nullable<System.DateTime> _DataAtualizacao;
		
		private System.Nullable<int> _PaginaIDOriginal;
		
		private string _ImagemShareFAcebook;
		
		private EntitySet<Pagina> _Paginas;
		
		private EntityRef<Pagina> _Pagina1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPaginaIDChanging(int value);
    partial void OnPaginaIDChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnResumoChanging(string value);
    partial void OnResumoChanged();
    partial void OnImagemChanging(string value);
    partial void OnImagemChanged();
    partial void OnHTMLChanging(string value);
    partial void OnHTMLChanged();
    partial void OnIsAtivaChanging(bool value);
    partial void OnIsAtivaChanged();
    partial void OnDataCriacaoChanging(System.DateTime value);
    partial void OnDataCriacaoChanged();
    partial void OnDataAtualizacaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataAtualizacaoChanged();
    partial void OnPaginaIDOriginalChanging(System.Nullable<int> value);
    partial void OnPaginaIDOriginalChanged();
    partial void OnImagemShareFAcebookChanging(string value);
    partial void OnImagemShareFAcebookChanged();
    #endregion
		
		public Pagina()
		{
			this._Paginas = new EntitySet<Pagina>(new Action<Pagina>(this.attach_Paginas), new Action<Pagina>(this.detach_Paginas));
			this._Pagina1 = default(EntityRef<Pagina>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaginaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PaginaID
		{
			get
			{
				return this._PaginaID;
			}
			set
			{
				if ((this._PaginaID != value))
				{
					this.OnPaginaIDChanging(value);
					this.SendPropertyChanging();
					this._PaginaID = value;
					this.SendPropertyChanged("PaginaID");
					this.OnPaginaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resumo", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string Resumo
		{
			get
			{
				return this._Resumo;
			}
			set
			{
				if ((this._Resumo != value))
				{
					this.OnResumoChanging(value);
					this.SendPropertyChanging();
					this._Resumo = value;
					this.SendPropertyChanged("Resumo");
					this.OnResumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagem", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Imagem
		{
			get
			{
				return this._Imagem;
			}
			set
			{
				if ((this._Imagem != value))
				{
					this.OnImagemChanging(value);
					this.SendPropertyChanging();
					this._Imagem = value;
					this.SendPropertyChanged("Imagem");
					this.OnImagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTML", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HTML
		{
			get
			{
				return this._HTML;
			}
			set
			{
				if ((this._HTML != value))
				{
					this.OnHTMLChanging(value);
					this.SendPropertyChanging();
					this._HTML = value;
					this.SendPropertyChanged("HTML");
					this.OnHTMLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAtiva", DbType="Bit NOT NULL")]
		public bool IsAtiva
		{
			get
			{
				return this._IsAtiva;
			}
			set
			{
				if ((this._IsAtiva != value))
				{
					this.OnIsAtivaChanging(value);
					this.SendPropertyChanging();
					this._IsAtiva = value;
					this.SendPropertyChanged("IsAtiva");
					this.OnIsAtivaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCriacao", DbType="DateTime NOT NULL")]
		public System.DateTime DataCriacao
		{
			get
			{
				return this._DataCriacao;
			}
			set
			{
				if ((this._DataCriacao != value))
				{
					this.OnDataCriacaoChanging(value);
					this.SendPropertyChanging();
					this._DataCriacao = value;
					this.SendPropertyChanged("DataCriacao");
					this.OnDataCriacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAtualizacao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataAtualizacao
		{
			get
			{
				return this._DataAtualizacao;
			}
			set
			{
				if ((this._DataAtualizacao != value))
				{
					this.OnDataAtualizacaoChanging(value);
					this.SendPropertyChanging();
					this._DataAtualizacao = value;
					this.SendPropertyChanged("DataAtualizacao");
					this.OnDataAtualizacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaginaIDOriginal", DbType="Int")]
		public System.Nullable<int> PaginaIDOriginal
		{
			get
			{
				return this._PaginaIDOriginal;
			}
			set
			{
				if ((this._PaginaIDOriginal != value))
				{
					if (this._Pagina1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPaginaIDOriginalChanging(value);
					this.SendPropertyChanging();
					this._PaginaIDOriginal = value;
					this.SendPropertyChanged("PaginaIDOriginal");
					this.OnPaginaIDOriginalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagemShareFAcebook", DbType="VarChar(255)")]
		public string ImagemShareFAcebook
		{
			get
			{
				return this._ImagemShareFAcebook;
			}
			set
			{
				if ((this._ImagemShareFAcebook != value))
				{
					this.OnImagemShareFAcebookChanging(value);
					this.SendPropertyChanging();
					this._ImagemShareFAcebook = value;
					this.SendPropertyChanged("ImagemShareFAcebook");
					this.OnImagemShareFAcebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pagina_Pagina", Storage="_Paginas", ThisKey="PaginaID", OtherKey="PaginaIDOriginal")]
		public EntitySet<Pagina> Paginas
		{
			get
			{
				return this._Paginas;
			}
			set
			{
				this._Paginas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pagina_Pagina", Storage="_Pagina1", ThisKey="PaginaIDOriginal", OtherKey="PaginaID", IsForeignKey=true)]
		public Pagina Pagina1
		{
			get
			{
				return this._Pagina1.Entity;
			}
			set
			{
				Pagina previousValue = this._Pagina1.Entity;
				if (((previousValue != value) 
							|| (this._Pagina1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pagina1.Entity = null;
						previousValue.Paginas.Remove(this);
					}
					this._Pagina1.Entity = value;
					if ((value != null))
					{
						value.Paginas.Add(this);
						this._PaginaIDOriginal = value.PaginaID;
					}
					else
					{
						this._PaginaIDOriginal = default(Nullable<int>);
					}
					this.SendPropertyChanged("Pagina1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Paginas(Pagina entity)
		{
			this.SendPropertyChanging();
			entity.Pagina1 = this;
		}
		
		private void detach_Paginas(Pagina entity)
		{
			this.SendPropertyChanging();
			entity.Pagina1 = null;
		}
	}
}
#pragma warning restore 1591
